apiVersion: v1
kind: ConfigMap
data:
  DB_HOST: 34.76.79.112
  DB_NAME: flights_covid
  DB_PORT: "5432"
  OUT_PORT: "30054"
  LOG_PATH: "/home/logging/logs"
metadata:
  name: logging-config
  namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aeilko/Documents/Uni/Cloud Computing/Project/cloud-computing/deployments/log"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      type: microservice
      app: logging
  template:
    metadata:
      labels:
        type: microservice
        app: logging
    spec:
      volumes:
        - name: log-pv-storage
          persistentVolumeClaim:
            claimName: log-pv-claim
      containers:
      - name: logging
        image: logging
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-login
                key: user
                optional: false
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-login
                key: pass
                optional: false
        envFrom:
          - configMapRef:
              name: logging-config
        volumeMounts:
          - mountPath: "/home/logging/logs"
            name: log-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: logging-endpoint
  namespace: default
  labels:
    type: microservice
    app: logging
spec:
  selector:
    type: microservice
    app: logging
  ports:
  - port: 30054
    protocol: TCP
  type: ClusterIP