openapi: "3.0.2"
info:
  title: "COVID Flights API"
  description: "Get the data related to flights during the last Covid pandemia"
  version: "1.0"


servers:
- url: "Not Implemented"

paths:
  /airport:
    get:
      tags:
      - Airports And Flights
      summary: "Get all the airports "
      description: "Access all the airports in the data base"
      operationId: AllAirportData
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'


  /allFlights:
    get:
      tags:
      - Airports And Flights
      summary: "Get all flights from a certain day"
      description: "Access all flights from a specific day"
      operationId: AllFlightsData
      parameters:
        - $ref: '#/components/parameters/date'

      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/array'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Not found
                type: string
                example: Not found

  /flightsStatistics:
    get:
      tags:
      - Airports And Flights
      summary: "Get all flights from an airport in a certain day"
      description: "Access all flights from an airport in a specific day"
      operationId: AllFlightsAirportData
      parameters:
        - $ref: '#/components/parameters/date'
        - $ref: '#/components/parameters/airport'

      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/array'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Not found
                type: string
                example: Not found

  /covidCases:
    get:
      tags:
      - Covid Cases
      summary: "Get the number of covid cases in europe on a certain day"
      description: "Get the number of covid cases in europe on a certain day"
      operationId: covidCasesEurope
      parameters:
        - $ref: '#/components/parameters/date'

      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Weather not found
                type: string
                example: Not found

  /covidCases/{airportID}:
    get:
      tags:
      - Covid Cases
      summary: "Get the number of covid cases in a certain airport's area"
      description: "Get the number of covid cases in an certain airport specifing its ID"
      operationId: covidCasesEurope
      parameters:
        - $ref: '#/components/parameters/airport'
        - $ref: '#/components/parameters/area_level'
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200'
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: airport not found
                type: string
                example: Not found


security:
- app_id: []

tags:
  - name: Airports And Flights
    description: "Get data from all the airports"
  - name: Covid Cases
    description: "Get data from covid cases in europe in a specific day"

components:

  parameters:

    date:
      name: Date
      in: query
      description: "Format DD/MM/YYYY"
      schema:
        type: string

    airport:
      name: airport
      in: query
      description: "Airport ID"
      schema:
        type: integer

    area_level:
      name: area_level:
      in: query
      description: "Level of the area around the airport (1=county, 2=state, 3=country)"
      schema:
        type: integer

  schemas:
    "200":
      title: Successful response
      type: object

      properties:
        coord:
          $ref: '#/components/schemas/Coord'

        airport:
          type: object
          items:
            $ref: '#/components/schemas/Airport'
          description: An airport

        flight:
          type: object
          items:
            $ref: '#/components/schemas/Flight'
          description: A flight


    Airport:
      titile: Airport
      type: object
      properties:
        id:
          type: integer
          description: Airport id
          format: int32
          example: 803

    Flight:
      titile: Flight
      type: object
      properties:
        id:
          type: integer
          description: Flight id
          format: int32
          example: 803
        dest:
          type: object
          description: Destination airport id
          format: int32
          example: 803
        src:
          type: object
          description: Source airport id
          format: int32
          example: 803
