version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgis_db_small
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
      - init_sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - ingest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  #ingestion:
  #  image: ingest
  #  networks:
  #    - ingest
  #  env_file:
  #    - .env
  #  volumes:
  #    - type: volume
  #      target: /home/ingest/datasets
volumes:
  dbdata:
  init_sql:
  datasets:
networks:
  ingest: