version: '3'

services:
  db:
    image: postgis/postgis
    container_name: postgis_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - ingest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  dbdata:
  datasets:
networks:
  ingest: