apiVersion: v1
kind: ConfigMap
data:
  DB_HOST: 34.76.79.112
  DB_NAME: flights_covid
  DB_PORT: "5432"
  OUT_PORT: "30052"
metadata:
  name: data-analysis-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analysis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      type: microservice
      app: data-analysis
  template:
    metadata:
      labels:
        type: microservice
        app: data-analysis
    spec:
      containers:
      - name: data-analysis
        image: europe-west1-docker.pkg.dev/cloud-computing-347913/cloud-computing-repo/data_analysis:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-login
                key: user
                optional: false
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-login
                key: pass
                optional: false
        envFrom:
          - configMapRef:
              name: data-analysis-config

---
apiVersion: v1
kind: Service
metadata:
  name: data-analysis-endpoint
  namespace: default
  labels:
    type: microservice
    app: data-analysis
spec:
  selector:
    type: microservice
    app: data-analysis
  ports:
  - port: 30052
    protocol: TCP
  type: ClusterIP
