apiVersion: v1
kind: ConfigMap
data:
  DB_HOST: 172.18.176.3
  DB_NAME: flights_covid
  DB_PORT: "5432"
  OUT_PORT: "30051"
metadata:
  name: data-delivery-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-delivery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      type: microservice
      app: data-delivery
  template:
    metadata:
      labels:
        type: microservice
        app: data-delivery
    spec:
      serviceAccountName: cloud-computing-cluster-service-account
      containers:
      - name: data-delivery
        image: europe-west1-docker.pkg.dev/cloud-computing-347913/cloud-computing-repo/data_delivery:latest
        imagePullPolicy: Always
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-login
                key: user
                optional: false
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-login
                key: pass
                optional: false
        envFrom:
          - configMapRef:
              name: data-delivery-config
---
apiVersion: v1
kind: Service
metadata:
  name: data-delivery-endpoint
  namespace: default
  labels:
    type: microservice
    app: data-delivery
spec:
  selector:
    type: microservice
    app: data-delivery
  ports:
  - port: 30051
    protocol: TCP
  type: ClusterIP
