apiVersion: v1
kind: ConfigMap
data:
  DB_HOST: 34.76.79.112
  DB_NAME: flights_covid
  DB_PORT: "5432"
  OUT_PORT: "30054"
metadata:
  name: logging-config
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      type: microservice
      app: logging
  template:
    metadata:
      labels:
        type: microservice
        app: logging
    spec:
      containers:
      - name: logging
        image: europe-west1-docker.pkg.dev/cloud-computing-347913/cloud-computing-repo/logging:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-login
                key: user
                optional: false
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-login
                key: pass
                optional: false
        envFrom:
          - configMapRef:
              name: logging-config

---
apiVersion: v1
kind: Service
metadata:
  name: logging-endpoint
  namespace: default
  labels:
    type: microservice
    app: logging
spec:
  selector:
    type: microservice
    app: logging
  ports:
  - port: 30054
    protocol: TCP
  type: ClusterIP
